name: golangci-lint
on: [push, pull_request]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37.1
          args: --skip-dirs=examples,proxy/protocol/dubbo --out-format=colored-line-number --skip-files=.*_test.go$