name: Merge check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build github.com/apache/servicecomb-mesher/cmd/mesher

    - name: UT
      run: |
        bash -x scripts/travis/unit_test.sh