# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Router rules and fault injection rules are moved to router.yaml
#plugin:
#  destinationResolver:
#    http: host # how to turn host to destination name. default to service name，

admin: #admin API
  goRuntimeMetrics : true # enable metrics
  enable: true

## enable pprof to profile mesher runtime
#pprof:
#  enable: false

#mesher:
#  ingress:
#    type: servicecomb
#    rule:
#      http: |
#        - host: example.com
#          limit: 30
#          apiPath: /some/api
#          service:
#            name: example
#            redirectPath: /another/api
#            port:
#              name: http-legacy
#              value: 8080
#        - apiPath: /sayerror/api
#          service:
#            name: Server
#            redirectPath: /sayerror
#            port:
#              name: http
#              value: 8080
#        - apiPath: /some/api
#          service:
#            name: Server
#            port:
#              name: http
#              value: 8080